### ISSUE TITLE
Create a new experiment to bundle admin package and add to demo

### ISSUE THREAD

**Issue by webcrumbs-community** [webcrumbs-community/webcrumbs#102]
We've successfully built `/core/experiment-1` that integrates plugins into the admin package. Now we want to create an experiment to bundle admin package and add to demo.

_This is a sequence of @webcrumbs-community in https://github.com/webcrumbs-community/webcrumbs/issues/51_

### What Needs to Be Done?

We want to duplicate `/core/experiment-1` and name it `experiment-x` (where x is the next available number). The goal here is to make the `/admin` package built with NextJS exposed as a Module Federation. Subsequently, we aim to import it into the `/demo` package, preferably with a script tag.

### Why Is This Important?

This will give us a scalable and modular architecture for the `/packages/admin` package. It'll enable easier integration and updates, while allowing the `/packages/demo` to access admin functionalities effortlessly. This could potentially be a game-changer in how we manage dependencies and features across our packages.

### Skills or Needed
- JavaScript
- NextJS
- Module Federation
- or curiosity to learn the skills needed

### Requirements
[ ] Duplicate `/core/experiment-1` and name it `/core/experiment-x`.
[ ] Work on `/core/experiment-x` to expose `/packages/admin` as a Module Federation.
[ ] Import the federated module into `/packages/demo` via a script tag.

Help us put the gears in motion for this next phase of WebCrumbs. Come on over to our GitHub repo and be a part of this exciting chapter!

**Comment by rovoskarl** [comment]
Do I need to create a /packages/demo?

**Comment by webcrumbs-community** [comment]
Yes, please.

**Comment by rovoskarl** [comment]
Can you give me permission to webcrumbs-community/webcrumbs.git? I have implemented a demo and I want to create a new branch and submit it.

**Comment by webcrumbs-community** [comment]
Hi, @rovoskarl. Could you fork it and then PR us?

**Comment by rovoskarl** [comment]
sure Discuss here https://github.com/webcrumbs-community/webcrumbs/pull/118
core/experiment-2/plugins is a remote shared used in core/experiment-2/admin

**Comment by dew-dr0p** [comment]
This is not completely solved, right? Would love to jump in. Don't know much about module federation yet, but I'll do a quick brushup to see how I can contribute.

**Comment by dew-dr0p** [comment]
@webcrumbs-community some things to consider:
* Does the module have to be loaded using a script tag?
There are some security implications to that. It poses more threat, though I think we might be able to mitigate a number of them, are there better methods we could use?
I understand the need to make it easy to use by potential users especially users with no code background.

**Comment by webcrumbs-community** [comment]
Hi @dew-dr0p,

Absolutely, ease of use is key for us, but not at the expense of security. We're looking into best practices for script tag safety and welcome any suggestions you might have. Let's prioritize a seamless user experience and work in security in parallel.

Thanks for your vigilance!

**Comment by dew-dr0p** [comment]
I'm having issues implementing Module Federation with the admin package considering it's using Next.js 14, the module federation package currently only supports Next.js 12 and 13.
I'm still trying to figure out a work around, like maybe manually getting this done, but for the meantime any help would be really appreciated.
